# Generated by Django 5.1 on 2024-08-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='закрытость'),
        ),
    ]
