# Generated by Django 5.1 on 2024-08-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_is_closed_article_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='публичность'),
        ),
    ]
